version: '3'

services:
  #MySQL用コンテナ
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=M1ndfulness!
      - MYSQL_DATABASE=test
      - MySQL_USER=test
      - MYSQL_PASSWORD=test
  #php用コンテナ
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
